name: Trigger Datadog Incident
on:
  workflow_dispatch:
    inputs:
      title:
        type: string
      customerImpacted:
        type: boolean
        required: true
      customerImpactScope:
        type: string
        description: Required if customer_impacted:"true". A summary of the impact customers experienced during the incident.
      notificationHandleName:
        type: string
      notificationHandleEmail:
        type: string
      port_context:
        required: true
        type: string
jobs:
  create-entity-in-port-and-update-run:

    runs-on: ubuntu-latest
    steps:
      - name: Inform start of Datadog incident creation
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).run_id }}
          logMessage: Starting request to create Datadog incident

      - name: Create a Datadog incident
        id: datadog_incident
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ secrets.DD_API_URL }}/api/v2/incidents"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json", "DD-API-KEY": "${{ secrets.DD_API_KEY }}", "DD-APPLICATION-KEY": "${{ secrets.DD_APPLICATION_KEY }}"}'
          data: '{"data": {"type": "incidents", "attributes": {"customer_impact_scope": "${{ inputs.customerImpactScope }}", "customer_impacted": "${{ inputs.customerImpacted }}", "title": "${{ inputs.title }}", "notification_handles": [{"display_name": "${{ inputs.notificationHandleName }}", "handle": "${{ inputs.notificationHandleEmail }}"}]}}}'

      - name: Inform completion of Datadog incident creation
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).run_id }}
          logMessage: Finished request to create Datadog incident
      
      - name: Inform ingestion of Datadog incident into Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).run_id }}
          logMessage: Ingesting Datadog incident into Port

      - name: Convert dates to desired format
        id: format_date
        run: |
          customer_impact_start=$(date -d "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.customer_impact_start }}" -u +"%Y-%m-%dT%H:%M:%SZ")
          customer_impact_end=$(date -d "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.customer_impact_end }}" -u +"%Y-%m-%dT%H:%M:%SZ")
          created=$(date -d "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.created }}" -u +"%Y-%m-%dT%H:%M:%SZ")
          modified=$(date -d "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.modified }}" -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "customer_impact_start=${customer_impact_start}" >> $GITHUB_OUTPUT
          echo "customer_impact_end=${customer_impact_end}" >> $GITHUB_OUTPUT
          echo "created=${created}" >> $GITHUB_OUTPUT
          echo "modified=${modified}" >> $GITHUB_OUTPUT

      - name: UPSERT Entity
        uses: port-labs/port-github-action@v1
        with:
          identifier: ${{ fromJson(steps.datadog_incident.outputs.response).data.id }}
          title: ${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.title }}
          blueprint: ${{ fromJson(inputs.port_context).blueprint }}
          properties: |-
            {
              "customerImpactScope": "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.customer_impact_scope }}",
              "customerImpacted": "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.customer_impacted }}",
              "customerImpactStart": "${{ steps.format_date.outputs.customer_impact_start }}",
              "customerImpactEnd": "${{ steps.format_date.outputs.customer_impact_end }}",
              "createdBy": "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.created_by.data.attributes.name }}",
              "created": "${{ steps.format_date.outputs.created }}",
              "updatedAt": "${{ steps.format_date.outputs.modified }}",
              "customerImpactDuration": "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.customer_impact_duration }}",
              "timeToDetect": "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.time_to_detect }}",
              "timeToRepair": "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.time_to_repair }}",
              "severity": "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.severity }}",
              "state": "${{ fromJson(steps.datadog_incident.outputs.response).data.attributes.state }}"
            }
          relations: "{}"
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          runId: ${{ fromJson(inputs.port_context).run_id }}
    
      - name: Inform completion of Datadog incident ingestion into Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).run_id }}
          link: ${{ secrets.DD_API_URL }}/incidents/${{ fromJson(steps.datadog_incident.outputs.response).data.id }}
          logMessage: Finished request to ingest Datadog incident into Port

      - name: Inform of workflow completion
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).run_id }}
          logMessage: Workflow completed